### ISSUE TITLE
ACLs of a series (of a Moodle course) are not set by using schedule-and-upload workflow

### ISSUE THREAD

**Issue by mwuttke** [opencast/opencast-admin-interface#316]
I'm not sure whether the error is in the new admin ui, but I'm just going to assume that it's in the right place. When scheduling scheduled lecture recordings using the schedule-and-upload workflow, my colleague and I noticed that the assignment of a series (Moodle course ID) does not work correctly and the access rights for the Moodle course (Learner & Instructor) are not set. This means that at the end of the dialogue for setting up a planned lecture recording, the assignment of the planned recordings to the access rights (ACLs) for the selected Moodle course is simply missing.

**To Reproduce**
1. Create a new Event
2. Select _Schedule single event_ or _Schedule multiple events_
3. Select workflow _Process upon upload and schedule_
4. Select _Straight to publishing_
5. See the error (screen shot)
![screenshot_2024-04-02](https://github.com/opencast/opencast-admin-interface/assets/2102425/69e1a355-ce3e-4345-845d-5555f176389b)

**Expected behavior**
The workflow should run through without errors, i.e. the ACLs for the series should be set acording to the Moodle course and the ACLs there.
![Bildschirmfoto vom 2024-04-02 19-27-47](https://github.com/opencast/opencast-admin-interface/assets/2102425/8a0e7716-5302-4e47-8388-3e872c9801e1)

**Server environment:**
- OS: Debian 12/Bookworm
- Opencast Version: 15.3 (deb packages)
- Separate nodes for adminpresentation & 4 workers
- using Extron SMP

**Comment by Arnei** [comment]
Thanks for the report. This should be fixed by https://github.com/opencast/opencast-admin-interface/pull/300 in the next release, but I have not actually tested if it fixes your particular problem.

This is also likely not a problem with the `schedule-and-upload` workflow, as the "Zugriffsrichtlinie"-Tab is already not showing the correct roles and the workflow does not start until after you hit "Anlegen" on the last tab.

**Comment by mwuttke** [comment]
Sorry @Arnei, but I didn't get it. Do you see the differenc between the behaviour of the new admin ui and the old one?

Piri gave me the hint to the [patch](https://github.com/opencast/opencast-admin-interface/pull/300) from you. I tried it yesterday by using a new jar file for opencast-admin-ui-interface form the newest branch (admin-ui-picard) built by Piri. The error still occurred.

**Comment by Arnei** [comment]
> Sorry @Arnei, but I didn't get it. Do you see the differenc between the behaviour of the new admin ui and the old one?

What in particular did you not understand?
Yes, I do see the difference in behaviour.

> Piri gave me the hint to the https://github.com/opencast/opencast-admin-interface/pull/300 from you. I tried it yesterday by using a new jar file for opencast-admin-ui-interface form the newest branch (admin-ui-picard) built by Piri. The error still occurred.

So #300 does not fix your issue, good to know at least.

**Comment by mwuttke** [comment]
Thanks Arne for your answer.

> What in particular did you not understand? Yes, I do see the difference in behaviour.

In the "Zugriffsrichtlinie"-Tab in the old Admin UI  the correct roles are shown but not in the new Admin UI. I don't understand why. Therefore my question to you.

**Comment by Arnei** [comment]
> In the "Zugriffsrichtlinie"-Tab in the old Admin UI the correct roles are shown but not in the new Admin UI. I don't understand why. Therefore my question to you.

The new Admin UI should definitely show the correct roles, so that's a bug. As for why that bug occurs I do not know.

**Comment by mwuttke** [comment]
The PR #321 solve the problem. Thanks to Arne & Katrin! ;-)
